name: Android APK Build

on:
  push:
    branches: [ main ]
    tags:       # 推送 tag 时也触发（必须放在 push 下）
      - 'v*'
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}
  release:
    types: [published]

concurrency:
  group: apk-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK (Temurin 17)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          accept-android-sdk-licenses: true
          packages: |
            platforms;android-34
            build-tools;34.0.0
            platform-tools
            extras;android;m2repository
            extras;google;m2repository

      - name: Gradle build (assembleRelease)
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :app:assembleRelease --parallel --build-cache --warning-mode all
          gradle-version: wrapper
        env:
          GRADLE_OPTS: -Dorg.gradle.configuration-cache=true -Dorg.gradle.daemon=false -Dorg.gradle.jvmargs='-Xms512m -Xmx2048m'

      - name: Collect APKs
        run: |
          mkdir -p apk
          find app/build/outputs/apk -type f -name "*.apk" -print -exec cp {} apk/ \;
          echo "Found APKs:";
          ls -lh apk

      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tvbox-apks-${{ github.run_number }}
          path: apk/*.apk
          if-no-files-found: error

      - name: Summary
        run: |
          echo "# Build Summary" >> $GITHUB_STEP_SUMMARY
          echo "Generated APK 文件列表:" >> $GITHUB_STEP_SUMMARY
          ls -1 apk >> $GITHUB_STEP_SUMMARY

  # 可选：后续可添加签名与发布 Release 的 job（需配置密钥）。
